# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base:

facebook:
  app_id:
  app_secret:
google:
  client_id:
  client_secret:
github:
  client_id:
  client_secret:
twitter:
  api_key:
  api_secret: